import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossOrigin="anonymous"/>
      </head>
      <body className="container-fluid">
        <div className="row">
          <div className="col-2 border border-primary">
            Logo
          </div>
          <div className="col border border-primary">
            <Link href="/" >Home</Link>
            &nbsp;
            <Link href="/hospital" >Hospital</Link>
            &nbsp;
            <Link href="/doctor">Doctor</Link>
            &nbsp;
            <Link href="/paisents">Paisents</Link>
            &nbsp;
            <Link href="/treatment" prefetch={true}>Treatment</Link>
            {/* prefetch={true} pre-fatch data when you hower link tp treatment */}
            &nbsp;
            <Link href="/treatment/opdTreatment" prefetch={true} replace={true}>opdTreatment</Link>
            &nbsp;  
            <Link href="/treatment/subTreatment" >sub-treatment</Link>
          </div>
        </div>
        <div className="row">
          <div className="col-3 border border-primary">
            Side bar
          </div>
          <div className="col border border-primary">
            {children}
          </div>
        </div>
        <div className="row">
          <div className="col border border-primary">
            Footer
          </div>
        </div>
      </body>
    </html>
  );
}
