import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-slate-900 via-gray-900 to-black text-white min-h-screen`}
  >
    {/* Navbar */}
    <nav className="sticky top-0 z-50 backdrop-blur-lg bg-white/10 border-b border-white/10">
      <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
        
        {/* Logo */}
        <h1 className="text-xl font-bold tracking-wide">
          🚀 <span className="text-indigo-400">next </span>js
        </h1>

        {/* Links */}
        <div className="flex gap-6 text-sm font-medium">
          <Link
            href="/"
            className="relative group transition"
          >
            Home
            <span className="absolute left-0 -bottom-1 h-[2px] w-0 bg-indigo-400 transition-all group-hover:w-full"></span>
          </Link>

          <Link
            href="/Lab-20"
            className="relative group transition"
          >
            Lab-20
            <span className="absolute left-0 -bottom-1 h-[2px] w-0 bg-indigo-400 transition-all group-hover:w-full"></span>
          </Link>
          <Link
            href="/Lab-20"
            className="relative group transition"
          >
            Lab-21
            <span className="absolute left-0 -bottom-1 h-[2px] w-0 bg-indigo-400 transition-all group-hover:w-full"></span>
          </Link>
        </div>
      </div>
    </nav>

    {/* Page Content */}
    <main className="max-w-7xl mx-auto px-6 py-10">
      <div className="rounded-2xl bg-white/5 border border-white/10 shadow-xl p-6">
        {children}
      </div>
    </main>

    {/* Footer */}
    <footer className="text-center text-xs text-gray-400 py-6">
      © 2026 Ultra UI • Built with Tailwind CSS
    </footer>
  </body>
</html>

  );
}
